clining_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Локализация
    path("i18n/", include("django.conf.urls.i18n")),
    #
    path("admin/", admin.site.urls),
    path("req/", include("clireq.urls")),
    path("user/", include("users.urls", namespace="user")),
    path("", include("main.urls")),
]

clireq/urls.py
from django.urls import path
from clireq.views import create_request, request_history

app_name = "clireq"

urlpatterns = [
    path("create-request/", create_request, name="create_request"),
    path("request-history/", request_history, name="request_history"),
]

main/urls.py
from django.urls import path
from main.views import HomePageView, robots_txt

from django.contrib.sitemaps.views import sitemap
from main.sitemap import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", robots_txt, name="robots"),
]

users/urls.py
from django.urls import path
from users.views import register, LogoutView, UserLoginView

app_name = "user"

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.urls import reverse
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.conf import settings


class HomePageView(TemplateView):
    template_name = "main/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Главная страница"
        return context


def robots_txt(request):
    admin_url = reverse("admin:index")
    create_url = reverse("clireq:create_request")
    history_url = reverse("clireq:request_history")
    lines = [
        "User-Agent: *",
        f"Sitemap: {settings.SITE_URL}/sitemap.xml",  # Убедитесь, что SITE_URL задан в settings.py
        f"Disallow: {admin_url}",  # Запрет доступа к админке
        f"Disallow: {create_url}",  # Запрет доступа к созданию заявок
        f"Disallow: {history_url}",  # Запрет доступа к истории заявок
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

main/templates/components/_footer.html
<footer class="container">
    <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-lg-4 col-sm-12 col-md-12">
            <a href="https://electropribor.ru/"
               class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <span class="ms-2">©ООО "Мой Не Сам" 2025</span>
            </a>
        </div>
        <div class="container col-lg-4 col-sm-12 col-md-12">
            <div class="row justify-content-evenly">
                <!-- ВКонтакте -->
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 text-center social-icon-container">
                    <a href="https://vk.com/"
                       class="social-icon"
                       data-bs-toggle="tooltip"
                       data-bs-placement="bottom"
                       title="Группа во ВКонтакте">
                        <i class="fa-brands fa-vk fa-2x"></i>
                    </a>
                </div>
                <!-- Telegram -->
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 text-center social-icon-container">
                    <a href="https://web.telegram.org/a/"
                       class="social-icon"
                       data-bs-toggle="tooltip"
                       data-bs-placement="bottom"
                       title="Группа в телеграм">
                        <i class="fa-brands fa-telegram fa-2x"></i>
                    </a>
                </div>
                <!-- YouTube -->
                <div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 text-center social-icon-container">
                    <a href="https://www.youtube.com"
                       class="social-icon"
                       data-bs-toggle="tooltip"
                       data-bs-placement="bottom"
                       title="Ютуб канал">
                        <i class="fa-brands fa-youtube fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row contact-info text-center mt-3 justify-content-between text-balance">
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 text-center align-items-center">
                    <p>
                        <i class="fa-solid fa-envelope me-2"></i>
                        Email: <a href="mailto:yurafriend@mail.ru" class="text-dark fw-bolder">yurafriend@mail.ru</a>
                    </p>
                </div>
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 text-center align-items-center">
                    <p>
                        <i class="fa-solid fa-phone me-2"></i>
                        Телефон: <a href="tel:+71234567890" class="text-dark fw-bolder">+7 (123) 456-78-90</a>
                    </p>
                </div>
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 text-center align-items-center">
                    <p>
                        <i class="fa-solid fa-globe me-2"></i><a href="https://electropribor.ru/" class="text-dark fw-bolder">Сайт ООО "БНАЛ"</a>
                    </p>
                </div>
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 text-center align-items-center my-auto">
                    <p>
                        <i class="fa-solid fa-book me-2"></i><a href="https://electropribor.ru/privacy_policy/"
   class="text-dark fw-bolder">Политика</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

main/templates/components/_header.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-between">
            <div class="col-lg-3 col-xl-3 col-md-5 col-sm-5 col-lg-custom">
                <a href="{% url "home" %}" style="text-decoration:none;">
                    <div class="justify-content-between text-center d-sm-blocki align-items-center">
                        <div class="col-xl-4 col-lg-5 col-md-5 col-sm-6">
                            <svg width="7.5rem"
                                 height="7.5rem"
                                 viewBox="50 40 250 100"
                                 class="unique_1_looka-1j8o68f">
                                <defs id="unique_1_SvgjsDefs2097"></defs>
                                <g id="unique_1_SvgjsG2098" featurekey="symbolFeature-0" transform="matrix(1.8329406262676327,0,0,1.8329406262676327,83.35297043464676,-14.938465404869847)" fill="#ffffff">
                            <defs xmlns="http://www.w3.org/2000/svg"></defs><title xmlns="http://www.w3.org/2000/svg">100icons2017</title>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M33.16,29.63H23.78a.85.85,0,0,1-.85-.85V23.11a.85.85,0,0,1,.85-.85h9.38a.85.85,0,0,1,.85.85v5.67A.85.85,0,0,1,33.16,29.63Zm-8.53-1.7h7.68V24H24.63Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M33.59,23.38a.85.85,0,0,1-.79-1.16l2.12-5.4a.84.84,0,0,1,.13-.22c2.32-2.86,3.41-3.5,6.85-3.57V10.46H24.42a7.14,7.14,0,0,0-4.27,2.7c1.31.24,3.36.81,3.51,2.1l.65,7.19a.85.85,0,0,1-1.69.15l-.64-7a7.1,7.1,0,0,0-2.92-.85.85.85,0,0,1-.85-.85c0-2.39,4-5,6.17-5.1H42.75a.85.85,0,0,1,.85.85v4.25a.85.85,0,0,1-.85.85c-3.56,0-4.19.27-6.29,2.85l-2.07,5.28A.85.85,0,0,1,33.59,23.38Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M47.3,15H42.75a.85.85,0,0,1-.85-.85V9a.85.85,0,0,1,.85-.85H47.3a.85.85,0,0,1,.85.85v5.13A.85.85,0,0,1,47.3,15Zm-3.7-1.7h2.85V9.85H43.6Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M43.5,24.8A2.8,2.8,0,0,1,41.55,24L41,23.5c-1.57-1.39-4.19-3.73-3.81-7.86a.85.85,0,0,1,1.69.16c-.3,3.27,1.75,5.1,3.25,6.43l.62.57a1.15,1.15,0,0,0,1.66-.13,1.07,1.07,0,0,0,.19-.93,24,24,0,0,1-.4-7.7.85.85,0,0,1,1.69.2,22.67,22.67,0,0,0,.36,7.07,2.76,2.76,0,0,1-.49,2.4A2.8,2.8,0,0,1,43.5,24.8Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M17.09,73.73h0a.85.85,0,0,1-.82-.88c0-1.43.06-2.8.08-4.09.1-8.77.18-15.11,9.66-16.06,10.26-1,14.44,2.59,14.61,2.75a.85.85,0,0,1-1.13,1.27c-.06-.05-3.91-3.27-13.32-2.33-8,.8-8,5.62-8.13,14.39,0,1.3,0,2.68-.08,4.13A.85.85,0,0,1,17.09,73.73Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M71.89,27.19a6.6,6.6,0,1,1,6.6-6.6A6.6,6.6,0,0,1,71.89,27.19Zm0-11.49a4.9,4.9,0,1,0,4.9,4.9A4.9,4.9,0,0,0,71.89,15.7Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M69.16,21.45a.85.85,0,0,1-.85-.85A3.58,3.58,0,0,1,71.89,17a.85.85,0,1,1,0,1.7A1.88,1.88,0,0,0,70,20.6.85.85,0,0,1,69.16,21.45Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M45.72,86.1a.85.85,0,0,1-.85-.85,3.58,3.58,0,0,1,3.58-3.58.85.85,0,1,1,0,1.7,1.88,1.88,0,0,0-1.88,1.88A.85.85,0,0,1,45.72,86.1Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M65.1,91.85a6.55,6.55,0,0,1-5.58-3.08,4.49,4.49,0,0,1-5.38-.19,6.59,6.59,0,0,1-10.7,1,4.36,4.36,0,1,1-.74-8.65,4.41,4.41,0,0,1,.74.06,6.59,6.59,0,0,1,10.7,1,4.49,4.49,0,0,1,5.38-.19,6.59,6.59,0,0,1,10.73-.61,4.43,4.43,0,0,1,4.22.79A4.77,4.77,0,0,1,76,81.68a4.83,4.83,0,1,1-3.74,7.89,4.32,4.32,0,0,1-2-.19A6.56,6.56,0,0,1,65.1,91.85ZM59.75,86.5h.11a.85.85,0,0,1,.68.53,4.89,4.89,0,0,0,8.69.82.85.85,0,0,1,1.13-.29,2.6,2.6,0,0,0,2,.23.85.85,0,0,1,1,.37A3.13,3.13,0,1,0,76,83.38a3.09,3.09,0,0,0-1.35.31.85.85,0,0,1-1-.2,2.7,2.7,0,0,0-3.27-.56.85.85,0,0,1-1.13-.29,4.89,4.89,0,0,0-8.69.83.85.85,0,0,1-1.47.2,2.63,2.63,0,0,0-2.12-1.07,2.67,2.67,0,0,0-2.3,1.33.83.83,0,0,1-.83.42.85.85,0,0,1-.72-.58,4.89,4.89,0,0,0-8.64-1.34.85.85,0,0,1-1,.31,2.66,2.66,0,1,0-.81,5.19,2.69,2.69,0,0,0,.82-.13.85.85,0,0,1,.95.31,4.89,4.89,0,0,0,8.64-1.34.85.85,0,0,1,1.54-.17,2.67,2.67,0,0,0,2.3,1.33,2.63,2.63,0,0,0,2.12-1.07A.85.85,0,0,1,59.75,86.5Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M62.38,86.1a.85.85,0,0,1-.85-.85,3.58,3.58,0,0,1,3.58-3.58.85.85,0,1,1,0,1.7,1.88,1.88,0,0,0-1.88,1.88A.85.85,0,0,1,62.38,86.1Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M76.78,48A5.22,5.22,0,1,1,82,42.83,5.22,5.22,0,0,1,76.78,48Zm0-8.74a3.52,3.52,0,1,0,3.52,3.52A3.52,3.52,0,0,0,76.78,39.31Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M75.42,44a.85.85,0,0,1-.85-.85,2.54,2.54,0,0,1,2.53-2.53.85.85,0,1,1,0,1.7.84.84,0,0,0-.83.83A.85.85,0,0,1,75.42,44Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M61.63,60.34a5.22,5.22,0,1,1,5.22-5.22A5.22,5.22,0,0,1,61.63,60.34Zm0-8.74a3.52,3.52,0,1,0,3.52,3.52A3.52,3.52,0,0,0,61.63,51.61Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M60.27,56.3a.85.85,0,0,1-.85-.85A2.54,2.54,0,0,1,62,52.92a.85.85,0,1,1,0,1.7.83.83,0,0,0-.83.83A.85.85,0,0,1,60.27,56.3Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M56.76,29.58a.85.85,0,0,1-.85-.85V24.9a.85.85,0,0,1,1.7,0v3.83A.85.85,0,0,1,56.76,29.58Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M56.76,38.86a.85.85,0,0,1-.85-.85V34.18a.85.85,0,0,1,1.7,0V38A.85.85,0,0,1,56.76,38.86Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M54,32.3H50.21a.85.85,0,1,1,0-1.7H54a.85.85,0,1,1,0,1.7Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M63.32,32.3H59.49a.85.85,0,1,1,0-1.7h3.83a.85.85,0,1,1,0,1.7Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M87.34,84.85H80a.85.85,0,1,1,0-1.7h6.52V70.42H52.05V79a.85.85,0,0,1-1.7,0V69.57a.85.85,0,0,1,.85-.85H87.34a.85.85,0,0,1,.85.85V84A.85.85,0,0,1,87.34,84.85Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M76.66,75.94H52.51a.85.85,0,1,1,0-1.7H76.66a.85.85,0,1,1,0,1.7Z" style="fill: #ffffff;">
                            </path>
                            <path xmlns="http://www.w3.org/2000/svg" class="a" d="M35.77,90.67H21.18a9.37,9.37,0,0,1-9.37-9.36V61.65A36.84,36.84,0,0,1,13.9,49.41l4.47-16.69a7.1,7.1,0,0,1,6.7-4.79h6.81a7.09,7.09,0,0,1,6.68,4.73l4.23,16a41.58,41.58,0,0,1,2.35,13.82V81.3a.85.85,0,0,1-.23.58,5,5,0,0,0-.43.52.85.85,0,0,1-1,.31,2.66,2.66,0,0,0-2.26,4.75.85.85,0,0,1,0,1.4A9.3,9.3,0,0,1,35.77,90.67Zm-10.7-61A5.39,5.39,0,0,0,20,33.22L15.52,49.91a35.31,35.31,0,0,0-2,11.74V81.31A7.67,7.67,0,0,0,21.18,89H35.77a7.61,7.61,0,0,0,3.61-.9A4.36,4.36,0,0,1,43.43,81V62.49a40.05,40.05,0,0,0-2.27-13.32l-4.23-16a5.37,5.37,0,0,0-5.06-3.53Z" style="fill: #ffffff;">
                            </path>
                            </g>
                        </svg>
                    </div>
                    <div class="col-xl-8 col-lg-6 col-md-5 col-sm-6">
                        <h5>Мой Не Сам</h5>
                    </div>
                </div>
            </a>
        </div>
        <div class="text-end align-items-center mt-2">
            <button class="navbar-toggler d-lg-none"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="nav col-lg-7 col-md-12 col-sm-12 justify-content-evenly menu-links">
            {% if request.user.is_authenticated %}
                <a class="d-block text-center align-items-center custom-header-link btn btn-outline-primary pb-1"
                   href="{% url "clireq:request_history" %}">
                    <i class="fa-solid fa-list-ul"></i>
                    <p class="text-white fw-bold custom-link mb-1">Создание заявки</p>
                </a>
                <a class="d-block text-center align-items-center custom-header-link btn btn-outline-primary pb-1"
                   href="{% url "clireq:create_request" %}">
                    <i class="fa-solid fa-pencil"></i>
                    <p class="text-white fw-bold custom-link mb-1">Формирование заявки</p>
                </a>
                {% if request.user.is_admin %}
                    <a class="d-block text-center align-items-center custom-header-link btn btn-outline-warning pb-1"
                       href="{% url "admin:index" %}">
                        <i class="fa-solid fa-book"></i>
                        <p class="text-white fw-bold custom-link mb-1">Админ панель</p>
                    </a>
                {% endif %}
                 <a class="d-block text-center align-items-center custom-header-link btn btn-outline-danger pb-1"
                   href="{% url "user:logout" %}">
                    <i class="fa-solid fa-door-open"></i>
                    <p class="text-white fw-bold custom-link mb-1">Выйти</p>
                </a>
            {% else %}
                <a href="{% url "user:login" %}"
                   class="btn btn-outline-warning btn-custom-users">Авторизоваться</a>
                <a href="{% url "user:register" %}"
                   class="btn btn-outline-warning btn-custom-users">Зарегистрироваться</a>
            {% endif %}
        </div>
    </div>
</div>
<!-- Бургер меню -->
</nav>
</div>
</div>
<!-- Мобильное меню -->
<div class="collapse navbar-collapse d-lg-none" id="navbarNav">
    <div class="navbar-nav flex-column navbario_mobile">
        {% if request.user.is_authenticated %}
            <a class="nav-item nav-link text-center align-items-center custom-header-link btn btn-outline-primary pb-1"
               href="{% url "clireq:request_history" %}">
                <i class="fa-solid fa-pencil"></i>
                <p class="text-white fw-bold custom-link mb-1">Создание заявки</p>
            </a>
            <a class="nav-item nav-link text-center align-items-center custom-header-link btn btn-outline-primary pb-1"
               href="{% url "clireq:create_request" %}">
                <i class="fa-solid fa-pencil"></i>
                <p class="text-white fw-bold custom-link mb-1">Формирование заявки</p>
            </a>
            {% if request.user.is_admin %}
                <a class="nav-item nav-link text-center align-items-center custom-header-link btn btn-outline-warning pb-1"
                   href="{% url "admin:index" %}">
                    <i class="fa-solid fa-book"></i>
                    <p class="text-white fw-bold custom-link mb-1">Админ панель</p>
                </a>
            {% endif %}
            <a class="nav-item nav-link text-center align-items-center custom-header-link btn btn-outline-danger pb-1"
               href="{% url "user:logout" %}">
                <i class="fa-solid fa-door-open"></i>
                <p class="text-white fw-bold custom-link mb-1">Выйти</p>
            </a>
        {% else %}
            <a href="{% url "user:login" %}"
               class="btn btn-outline-warning btn-custom-users">Авторизоваться</a>
            <a href="{% url "user:register" %}"
               class="btn btn-outline-warning btn-custom-users">Зарегистрироваться</a>
        {% endif %}
    </div>
</div>
</header>
{% include "_partials/_messages.html" %}