clining_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Локализация
    path("i18n/", include("django.conf.urls.i18n")),
    #
    path("admin/", admin.site.urls),
    path("req/", include("clireq.urls")),
    path("user/", include("users.urls", namespace="user")),
    path("", include("main.urls")),
]

clireq/urls.py
from django.urls import path
from clireq.views import create_request, request_history

app_name = "clireq"

urlpatterns = [
    path("create-request/", create_request, name="create_request"),
    path("request-history/", request_history, name="request_history"),
]

main/urls.py
from django.urls import path
from main.views import HomePageView, robots_txt

from django.contrib.sitemaps.views import sitemap
from main.sitemap import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", robots_txt, name="robots"),
]

clireq/models.py
from django.db import models
from users.models import CustomUser


class ServiceRequest(models.Model):
    STATUS_CHOICES = [
        ("rookie", "Новая заявка"),
        ("approve", "Подтверждено"),
        ("completed", "Выполнено"),
        ("cancelled", "Отменено"),
    ]
    SERVICE_CHOICES = [
        ("general_cleaning", "Общий клининг"),
        ("deep_cleaning", "Генеральная уборка"),
        ("post_construction", "Послестроительная уборка"),
        ("carpet_cleaning", "Химчистка ковров и мебели"),
    ]

    PAYMENT_CHOICES = [
        ("cash", "Наличные"),
        ("card", "Банковская карта"),
    ]
    user = models.ForeignKey(
        to=CustomUser,
        on_delete=models.CASCADE,
        related_name="service_requests",
        verbose_name="Пользователь",
    )
    address = models.CharField(max_length=255, verbose_name="Адрес")
    phone = models.CharField(max_length=18, verbose_name="Телефон")
    service_type = models.CharField(
        max_length=50,
        choices=SERVICE_CHOICES,
        verbose_name="Вид услуги",
        blank=True,
        null=True,
    )
    other_service = models.TextField(blank=True, null=True, verbose_name="Иная услуга")
    preferred_datetime = models.DateTimeField(verbose_name="Желаемая дата и время")
    payment_method = models.CharField(
        max_length=4, choices=PAYMENT_CHOICES, verbose_name="Тип оплаты"
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="rookie",
        verbose_name="Статус заявки",
    )
    cancellation_reason = models.TextField(
        blank=True, null=True, verbose_name="Причина отмены"
    )

    def __str__(self):
        return f"Заявка от {self.user} на {self.preferred_datetime}"

    class Meta:
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"
        ordering = ["-preferred_datetime"]
        db_table = "Заявки"

clireq/forms.py
import re
from django import forms
from django.core.exceptions import ValidationError
from .models import ServiceRequest
from datetime import datetime, timedelta


class ServiceRequestForm(forms.ModelForm):
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "+7(XXX)-XXX-XX-XX",
                "class": "form-control mb-2",
                "id": "id_phone",
            }
        ),
        label="Номер телефона",
    )
    other_service = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "rows": 3,
                "class": "form-control mb-2",
                "id": "id_other_service",
                "style": "display: none;",  # Скрываем поле по умолчанию
            }
        ),
        required=False,
        label="Описание иной услуги",
    )
    is_other_service = forms.BooleanField(
        required=False,
        label="Иная услуга",
        widget=forms.CheckboxInput(attrs={"id": "id_is_other_service"}),
    )

    class Meta:
        model = ServiceRequest
        fields = [
            "address",
            "phone",
            "service_type",
            "other_service",
            "preferred_datetime",
            "payment_method",
        ]
        widgets = {
            "address": forms.TextInput(
                attrs={
                    "class": "form-control mb-2",
                    "placeholder": "Введите адрес",
                    "id": "id_address",
                }
            ),
            "service_type": forms.Select(
                attrs={"class": "form-control mb-2", "id": "id_service_type"}
            ),
            "preferred_datetime": forms.DateTimeInput(
                attrs={
                    "type": "datetime-local",
                    "class": "form-control mb-2",
                    "id": "id_preferred_datetime",
                }
            ),
            "payment_method": forms.RadioSelect(attrs={"class": "form-check-input"}),
        }
        labels = {
            "address": "Адрес",
            "service_type": "Вид услуги",
            "preferred_datetime": "Желаемая дата и время",
            "payment_method": "Тип оплаты",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Убираем пустой выбор для payment_method
        self.fields["payment_method"].choices = [
            ("cash", "Наличные"),
            ("card", "Банковская карта"),
        ]
        self.fields["payment_method"].initial = "cash"  # Начальное значение
        now = datetime.now()
        self.fields["preferred_datetime"].widget.attrs.update(
            {
                "min": (now + timedelta(hours=1)).strftime("%Y-%m-%dT%H:%M"),
                "max": (now + timedelta(days=31)).strftime("%Y-%m-%dT%H:%M"),
            }
        )

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")

        # Удаляем все символы, кроме цифр
        normalized_phone = re.sub(r"[^\d]", "", phone)

        # Проверяем формат номера
        if len(normalized_phone) == 11 and normalized_phone.startswith("7"):
            return normalized_phone
        elif len(normalized_phone) == 11 and normalized_phone.startswith("8"):
            return normalized_phone
        else:
            raise ValidationError(
                "Неверный формат телефона. Используйте формат: +7(XXX)-XXX-XX-XX."
            )

    def clean_preferred_datetime(self):
        selected_datetime = self.cleaned_data["preferred_datetime"]
        # Удаляем временную зону, если она есть

        if selected_datetime and selected_datetime.tzinfo:
            selected_datetime = selected_datetime.replace(tzinfo=None)

        if selected_datetime < datetime.now():
            raise forms.ValidationError("Дата и время не могут быть в прошлом.")
        return selected_datetime

    def clean(self):
        cleaned_data = super().clean()
        is_other_service = cleaned_data.get("is_other_service")
        service_type = cleaned_data.get("service_type")
        other_service = cleaned_data.get("other_service")

        # Если выбран чекбокс "Иная услуга", поле "other_service" должно быть заполнено
        if is_other_service and not other_service:
            raise ValidationError("Пожалуйста, опишите иную услугу.")
        elif not is_other_service and not service_type:
            raise ValidationError("Выберите вид услуги или отметьте 'Иная услуга'.")

        return cleaned_data

clireq/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from .forms import ServiceRequestForm
from .models import ServiceRequest


@login_required
def create_request(request):
    if request.method == "POST":
        form = ServiceRequestForm(request.POST)
        if form.is_valid():
            service_request = form.save(commit=False)
            service_request.user = request.user  # Привязываем заявку к пользователю
            service_request.save()
            messages.success(request, "Успешное создание заявки")
            return redirect("clireq:request_history")
    else:
        form = ServiceRequestForm()
    return render(
        request,
        "clireq/create_request.html",
        {
            "form": form,
            "title": "Формирование заявки",
            "meta_description": (
                "Исправьте ошибки в форме, чтобы успешно создать заявку."
                if form.errors
                else "Создайте новую заявку на сайте. Укажите адрес, контактные данные, тип услуги и предпочтительное время для обработки вашего запроса."
            ),
            "meta_keywords": "создание заявки, форма заявки, отправка заявки, выбор услуги, контактные данные, предпочтительное время",
        },
    )


@login_required
def request_history(request):
    requests = ServiceRequest.objects.filter(user=request.user)
    return render(
        request,
        "clireq/request_history.html",
        {
            "requests": requests,
            "title": "Создание заявки",
            "meta_description": "Просмотрите историю ваших заявок на сайте. Здесь вы найдете информацию о статусе заявок, услугах и деталях оплаты.",
            "meta_keywords": "история заявок, статус заявки, услуги, оплата, отмена заявки, создание заявки",
        },
    )

clireq/templates/clireq/create_request.html
{% extends "base.html" %}
{% block content %}
    <div class="container col-11 col-sm-10 col-md-8 col-lg-6 col-xl-3 border border-2 rounded border-dark mt-2 p-xl-3 p-2">
        <h2 class="text-center pb-2">Формирование заявки</h2>
        <form method="post" class="text-center">
            {% csrf_token %}
            <div>
                {% for field in form %}
                    <!-- Исключаем поле other_service из цикла -->
                    {% if field.name != "other_service" %}
                        <div class="mb-2">
                            {% if field.name == "payment_method" %}
                                <!-- Отдельная обработка для поля выбора оплаты -->
                                <label class="form-label">{{ field.label }}</label>
                                <div class="w-75 mx-auto">
                                    {% for radio in field %}
                                        <div class="form-check form-switch">
                                            {{ radio.tag }}
                                            <label class="form-check-label">{{ radio.choice_label }}</label>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <div class="form-floating">
                                    {{ field }}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                </div>
                            {% endif %}
                            <!-- Вывод ошибок для конкретного поля -->
                            {% if field.errors %}<div class="text-danger small">{{ field.errors|striptags }}</div>{% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
                <!-- Отдельный блок для поля other_service -->
                <div class="text-center mb-3"
                     id="other_service_container"
                     style="display: none">
                    <label for="id_other_service" class="form-label">{{ form.other_service.label }}</label>
                    {{ form.other_service }}
                    <!-- Вывод ошибок для поля other_service -->
                    {% if form.other_service.errors %}
                        <div class="text-danger small">{{ form.other_service.errors|striptags }}</div>
                    {% endif %}
                </div>
            </div>
            <!-- Вывод общих ошибок формы -->
            {% if form.non_field_errors %}<div class="alert alert-danger">{{ form.non_field_errors }}</div>{% endif %}
            <div class="container row d-flex flex-wrap pt-2">
                <button class="btn btn-success w-75 mx-auto" type="submit">Отправить заявку</button>
            </div>
        </form>
    </div>
    <script>
    document.addEventListener("DOMContentLoaded", function () {
        const isOtherServiceCheckbox = document.getElementById("id_is_other_service");
        const otherServiceContainer = document.getElementById("other_service_container");
        const other = document.getElementById("id_other_service");

        // Проверяем, что элементы найдены
        if (isOtherServiceCheckbox && otherServiceContainer) {
            isOtherServiceCheckbox.addEventListener("change", function () {
                if (this.checked) {
                    otherServiceContainer.style.display = "block";
                    other.style.display = "block";
                } else {
                    otherServiceContainer.style.display = "none";
                    other.style.display = "none"
                }
            });
        } else {
            console.error("Элементы 'id_is_other_service' или 'other_service_container' не найдены.");
        }
    });
    </script>
{% endblock content %}

clireq/templates/clireq/request_history.html
{% extends "base.html" %}
{% load custom_filters %}
{% block content %}
    <div class="container">
        <p class="h2 mt-2">История ваших заявок</p>
        <!-- Список заявок -->
        {% if requests %}
            <div class="row justify-content-evenly pt-3 requests_container">
                {% for request in requests %}
                    <div class="col-lg-5 col-xl-5 col-md-8 col-sm-11 col-11 shadow-sm border border-3 {% if request.status == "cancelled" %} border-danger {% elif request.status == "completed" %} border-success {% elif request.status == "approve" %} border-primary {% else %} border-info {% endif %} rounded-2">
                        <div class="container border-bottom border-2 {% if request.status == "cancelled" %} border-danger {% elif request.status == "completed" %} border-success {% elif request.status == "approve" %} border-primary {% else %} border-info {% endif %} px-auto align-items-center pt-3">
                            <p class="h5 {% if request.status == "cancelled" %} mb-0 {% else %} pb-2 {% endif %}  text-balance">
                                Заявка на {{ request.preferred_datetime }}
                                <br>
                                Статус: {{ request.get_status_display }}
                                {% if request.status == "cancelled" %}
                                    <br>
                                    Причина отмены:
                                    <p class="fw-bolder text-balance text-danger my-0">{{ request.cancellation_reason }}</p>
                                {% endif %}
                            </p>
                        </div>
                        <div class="container row py-2">
                            <strong class="py-1">Адрес:</strong>
                            <p>{{ request.address }}</p>
                            <strong class="py-1">Телефон:</strong>
                            <p>{{ request.phone|format_phone }}</p>
                            <strong class="py-1">Услуга:</strong>
                            <p>
                                {% if request.service_type %}
                                    {{ request.get_service_type_display }}
                                {% else %}
                                    Иная услуга: {{ request.other_service }}
                                {% endif %}
                            </p>
                            <strong class="py-1">Дата и время:</strong>
                            <p>{{ request.preferred_datetime }}</p>
                            <strong class="py-1">Тип оплаты:</strong>
                            <p>{{ request.get_payment_method_display }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>У вас пока нет заявок.</p>
        {% endif %}
        <!-- Ссылка на создание новой заявки -->
        <div class="container text-center mx-auto mt-4">
            <a href="{% url 'clireq:create_request' %}" class="btn btn-outline-dark">Создать новую заявку</a>
        </div>
    </div>
{% endblock content %}